#!/usr/bin/env bash 
 
if [[ ! -e $HOME/.conda/envs/rnaseq_pipeline ]]; then
   conda env create --prefix $HOME/.conda/envs/rnaseq_pipeline -f /opt/apps/labs/mblab/software/rnaseq_pipeline/1.0/rnaseq_pipeline_environment.yml
fi
